---
build_from:
  aarch64: ghcr.io/hassio-addons/base-python/aarch64:18.0.0
  amd64: ghcr.io/hassio-addons/base-python/amd64:18.0.0
  armhf: ghcr.io/hassio-addons/base-python/armhf:18.0.0
  i386: ghcr.io/hassio-addons/base-python/i386:18.0.0
